### ISSUE TITLE
extractSchematic

### ISSUE THREAD

**Issue by gentlegiantJGC** [Khroki/MCEdit-Unified#634]
I believe there is a bug with the extractSchematic function where it adds a ! and then a coordinate from where the previous command was run from. 
Examples:
`execute @a 0 0 0 setblock 0 0 0`
`execute @a 0 0 0 fill 0 0 0 0 0 0`

in the tests I ran these became the following once extracted
`execute @a 0!33 0!-7 0!79 setblock 0!33 0!-7 0!79`
`execute @a 0!33 0!-7 0!79 fill 0!33 0!-7 0!79 0!33 0!-7 0!79`

I feel like this is an attempt to locate where the commands actually came from but I may be wrong.

Filter code used to extract and read the command from the extracted schematic
```
def perform(level, box, options):
	temp = level.extractSchematic(box)
	print temp.tileEntityAt(0, 0, 0)
```
Edit: I used a 1x1x1 selection which is why I hard coded the coordinates

**Comment by jobensingh** [comment]
You might want to point out which version of mcEdit you are running

**Comment by gentlegiantJGC** [comment]
This was tested with the latest build but the problem seems to have been around for a while

**Comment by jobensingh** [comment]
Ill try this out later when I get home and take a look at it

**Comment by naor2013** [comment]
It's not a bug, it's on purpose like that... When you paste it someplace it should remove those for you.
Do they create an error or an issue?

**Comment by robske110** [comment]
@naor2013 yes, it should try to change the coords. But they are corrupted

**Comment by gentlegiantJGC** [comment]
Well according to the docs you should be able to call that function and it will extract the box into a schematic exactly like it was in the world however it isn't like that.
If there is another function that simply extracts it to a schematic or another function it needs to be passed through to get it to that please can you let me know

**Comment by naor2013** [comment]
In the next release you should be able to use "level.extractSchematic(box, cancelCommandBlockOffset=True)" and it should fix the issue

**Comment by gentlegiantJGC** [comment]
thanks

**Comment by robske110** [comment]
This is not fixed. You just implemented a switch to disable this.
But sone people want this (WORKING)

**Comment by naor2013** [comment]
I don't understand your comment. What's the problem? Some people want the coords to change when moving command blocks but I added a switch to disable that, like you said... What is the issue with that?

**Comment by robske110** [comment]
The issue is that it does not work (if its enabled)

**Comment by naor2013** [comment]
That is not a bug, but a feature... The way we implemented offsetting with command blocks is by saving the old coords number and that's why it looked like that... If you want to remove that "!" signs, you'll have to give up on the offsetting things, that's why you have the choice to pick either offsetting, or cancel offsetting with the command blocks staying the same in the schematic

**Comment by robske110** [comment]
So you would have to run an filter removing " *!"

**Comment by naor2013** [comment]
No, I wrote how you can remove that with the next version, that's what I changed... You have the option as the filter-maker to not get those "!" in the schematic you create

**Comment by naor2013** [comment]
I don't think I understand your issue...
Can you please try to explain it?
