### ISSUE TITLE
MCEdit-Unified will not install on Ubuntu 16.04

### ISSUE THREAD

**Issue by Dain42** [Khroki/MCEdit-Unified#698]
When installation is attempted, it gives an error message:

```
Sorry, Python 2.7 setuptools not found.
No package will be installed by this script.
```

I've tracked this down to line 167940 in the .run install script, where it attempts to run the command which `easy_install-2.7 > /dev/null`. However, there is no `easy_install-2.7` command on Ubuntu, only `easy_install`, which when run with the `--version` flag says it's the version for Python 2.7.  Because the command doesn't exist, the script incorrectly determines that `setuptools` hasn't been installed, and it exits with the above message.

I've not tested this in other Linux distros, but given the close relationship between the Ubuntu and Debian distros, it's likely a problem on recent versions of Debian, too.

I was able to get around the issue by just creating a symlink from `easy_install-2.7 -> easy_install` in a location in my `$PATH`.

**Comment by LaChal** [comment]
Thank you for pointing this.

The fact is on other distros, `easy_install` may point to the Python 3+ installation, so `easy_install-2.7` has to be used.

A better handling for this will be implemented in the next version of the installer.

**Comment by LaChal** [comment]
A new release is available here http://www.mcedit-unified.net/.
As usual, some new features has been added and some bugs were fixed :smile:

**Comment by Aquaeyes** [comment]
Running Linux 16.04, no Mods and Minecraft 1.10, MCedit v1.5.5.0 - in which the bug was reportedly fixed in.
First, I ran the .run file from the desktop, pressed enter on 'I agree', 'Continue', 'Yes', and 'Yes'. This gave me an error stating that:

"Sorry, Python 2.7 setuptools not found.
No package will be installed by this script.
Install setuptools and retry."

I did 'sudo apt-get install python-setuptools' which seemed to work, and 'ln -s easy_install-2.7 easy_install', but it still doesn't seem to work.

Thank you for your time.

**Comment by Flexico** [comment]
This is still happening for me, with version 1.5.6.0. I'm running Mint 18.

**Comment by LaChal** [comment]
Can you post the log file, please?

You shall find it in `~/.local/log`.

**Comment by Flexico** [comment]
Log: [spoiler]2017-06-18:08:28:10-EDT | Starting MCEdit-Unified v1.5.6.0 installation.
2017-06-18:08:28:10-EDT | Command-line: install.pyc
2017-06-18:08:28:10-EDT | Parsing command-line arguments.
2017-06-18:08:28:10-EDT | Displaying disclaimer.
2017-06-18:08:28:11-EDT | Displaying readme file.
2017-06-18:08:28:14-EDT | Checking state of dependencies.
2017-06-18:08:28:14-EDT | Checking PyOpenGL.
2017-06-18:08:28:14-EDT | Checking ftputil.
2017-06-18:08:28:14-EDT | Checking numpy.
2017-06-18:08:28:15-EDT | Checking pillow.
2017-06-18:08:28:15-EDT | Checking pygame.
2017-06-18:08:28:16-EDT | Checking python-xlib.
2017-06-18:08:28:16-EDT | Checking pyyaml.
2017-06-18:08:28:16-EDT | * Libraries found and compliant:
2017-06-18:08:28:16-EDT |   - numpy is 1.11.0, is at least 1.8.1.
2017-06-18:08:28:16-EDT |   - pillow is 3.1.2, is at least 1.7.8.
2017-06-18:08:28:16-EDT |   - pygame is 1.9.1, is 1.9.1.
2017-06-18:08:28:16-EDT |   - python-xlib is 0.14, is at least 0.14.
2017-06-18:08:28:16-EDT | * Libraries found but must be upgraded:
2017-06-18:08:28:16-EDT |   - PyOpenGL is 3.0.2, should be at least 3.1.0.
2017-06-18:08:28:16-EDT |   - ftputil is 2.2.3, should be at least 3.2.
2017-06-18:08:28:16-EDT | * Libraries not found and must be installed:
2017-06-18:08:28:16-EDT |   - pyyaml: install one at least 3.10.
2017-06-18:08:28:17-EDT | Dependency installation required.
2017-06-18:08:28:19-EDT | User answer for dependencies installation: 0
2017-06-18:08:28:19-EDT | Deps install: yes_to_all: False; no_deps: False; a: True
2017-06-18:08:28:19-EDT | Installing dependencies.
2017-06-18:08:28:19-EDT | Checking easy_install.
2017-06-18:08:28:20-EDT | Could not find easy_install. Installation may be needed.
2017-06-18:08:28:20-EDT | Aborting
2017-06-18:08:28:26-EDT | Exiting with status 1[/spoiler]

I'm using MATE desktop. I have already installed python-pygame and python-setutools; I've used them for other programs and they worked fine.

**Comment by LaChal** [comment]
What happens when your enter `which easy_install` and `which easy_install-2.7` in a shell?

**Comment by Flexico** [comment]
flexico@ben2 ~ $ which easy_install
/usr/bin/easy_install
flexico@ben2 ~ $ which easy_install-2.7
flexico@ben2 ~ $

**Comment by Flexico** [comment]
Oh! I made a symbolic link to /usr/bin/easy_install as /usr/bin/easy_install-2.7 and ran the installer again and it worked!

**Comment by FinKsu** [comment]
Worked for me to make a symbolic link

**Comment by RossComputerGuy** [comment]
It's not working for me, I'm on Pop!_OS. `which easy_install` shows no entries despite `python-setuptools` package is installed.

**Comment by RossComputerGuy** [comment]
I made a file which exec's the file using python and it works until I get to this error:
```
-------------------------------------------------------------------------------
You will be asked where you want to move MCEdit-Unified.

If you don't want to move it, just hit 'ENTER'
If you enter `/foo/bar`, you will have a `/foo/bar/mcedit` directory.
If the path is not valid, you will be prompted for another one.
Paths can be relative or absolute.

Move MCEdit-Unified to: /home/ross

Traceback (most recent call last):
  File "../bin3/mcedit-1.5.6.0/install.py", line 1133, in <module>
TypeError: coercing to Unicode: need string or buffer, bool found
```
