### ISSUE TITLE
Data Value Issue When Importing PC Schematic Into PE

### ISSUE THREAD

**Issue by bman92102** [Khroki/MCEdit-Unified#800]
When importing a schematic from PC to PE, the data values of some blocks are lost, these include but are not limited to, Slabs, Double Slabs, Command Blocks, Hoppers, Concrete, Etc. It mainly occurs with data values 1, and 10-15. The weird thing is that this doesn't occur when transferring PE schematics to PE, only from PC to PE. This happens on all OSes and has been happening even before the new PE support. I know porting isn't a native feature yet, but this seems like a side effect of a bug as @neonerz said. Thanks! 😄

I have made a world for PC and PE to look at.
[PE (Slab/Trapdoor)](https://github.com/Khroki/MCEdit-Unified/files/1049863/Slab.Trapdoor.Test.zip)
[PC Trapdoor](https://github.com/Khroki/MCEdit-Unified/files/1049864/Trapdoor.Test.zip)
[PC Slabs](https://github.com/Khroki/MCEdit-Unified/files/1049865/Slab.Test.zip)

**Comment by neonerz** [comment]
A bit more info:

I wrote a filter to do the translations @bman92102 suggests above on trap doors. Updating the data values on a PC world before saving it as a schematic and loading it into a PE world seemed to make the actual states correct.

Here's a visual representation of the slabs bug.
http://i.imgur.com/WSgKJM8.png

The slabs on the left are a placed schematic before I actually import it into a PE world.
The slabs on the right are the same schematic, but I actually imported them.

As you can see, the the data values changed after importing the schematic. Starting from the top block to the bottom, this is how it seems to be remapping:

0 -> 0
1 -> 0
2 -> 2
3 -> 3
4 -> 4
5 -> 5
6 -> 0
7 -> 0
8 -> 8
9 -> 9
10 -> 0
11 -> 0
12 -> 0
13 -> 0
14 -> 8
15 -> 8

**Comment by LaChal** [comment]
Hmmm...

As discussed in other topics here, porting PE stuff to PC worlds and vice-versa is not natively supported yet.

@neonerz: if you can get a working filter, we may include it as a default filter in MCEdit. Let's talk about :smile:

**Comment by bman92102** [comment]
I know porting isn't natively supported yet, but maybe this could be used to help fix it in the future. This happened to more blocks than originally thought. It happens to droppers, and command blocks too. All slabs show when I made the world in PE, but when importing a schematic or a certain selection from the PC edition to the Pocket edition world, the conversion will mess up certain types of a block, and it is always the same ones. When copying from PE to PE, they do not mess up.

**Comment by neonerz** [comment]
I'd like to second this request. My filter is pretty much done, but issues like this make it less than useful since my filter can't fix the blocks due to the data getting reset at import.

Here's an example schematic:
[command-block-issue_2017-07-01--12-45-32.schematic.txt](https://github.com/Khroki/MCEdit-Unified/files/1117268/command-block-issue_2017-07-01--12-45-32.schematic.txt)
(drop the .txt extension).

When you import this schematic into a PE world the following happens:

Normal Command Blocks: all 12 data values show up correctly

Chain and Repeating Command Blocks: Any blocks with data value 1, 10, 11, 12, 13 (non-conditional up, and conditional north, south, west, east respectively) lose their data values and NBT data (gets reset to data value 0 with no nbt data)

This also happens on a bunch of other blocks as @bman92102 mentioned. Slabs, Dispensers, Droppers, etc. It almost seems like a bug in data handling, though it only seems to effect when importing a Java schematic into a PE world, or a PE schematic into a Java world.

I understand your focus isn't on conversion, but with the amount of blocks this effects, it makes me wonder if it what we are seeing is only a symptom of an underlining bug.

If necessary, here's the blocks.json we are using ( @bman92102 checked and double checked to make sure it wasn't related to this blocks.json. He tried fixing it in here as well, but couldn't. I also tested with the blocks.json that is included in the repo and had the same issue).
https://github.com/PathwayStudios/blocks.json

**Comment by neonerz** [comment]
Just confirmed the issue also effects concrete and concrete powder. Its starting to look like it's the same or very similar data values that get messed up across all blocks effected.

For Concrete and Concrete powder data values 1, 10-15 get reset to 0
For Chain and Repeating Command Blocks it's, 1, 10-13 (there is no 14 or 15)
For Slabs it's 1, 10-15
etc

**Comment by LaChal** [comment]
@neonerz In you filter, try to import the MCEdit embeded module `id_definitions` from `pymclevel`.
It contains a `version_defs_ids` dict in which keys are game version and values `MCEditDefsIds` instances with a `get_id` and `get_def` methods.

**Comment by neonerz** [comment]
Just to be clear here, the issue happens *before* I use my filter. The work flow is open Java map, export schematic, open PE map, import schematic, issue occurs.

Using the module id_definitions with that dict and class functions, all it's doing is printing out the blocks.json definitions.

`pprint.pprint(id_definitions.MCEditDefsIds("PE").get_def(id_definitions.MCEditDefsIds("PE").get_id(188)))`

```
{u'data': {u'0': {u'name': u'Repeating Command Block (Not Conditional, Down)',
                  u'tex_direction': {u'BACKWARD': [29, 5],
                                     u'BOTTOM': [22, 1],
                                     u'FORWARD': [29, 5],
                                     u'SIDES': [29, 5]}},
           u'1': {u'name': u'Repeating Command Block (Not Conditional, Up)',
                  u'tex_direction': {u'BACKWARD': [27, 5],
                                     u'FORWARD': [27, 5],
                                     u'SIDES': [27, 5],
                                     u'TOP': [22, 1]}},
           u'10': {u'name': u'Repeating Command Block (Conditional, North)',
                   u'tex_direction': {u'BOTTOM': [23, 5],
                                      u'FORWARD': [22, 1],
                                      u'LEFT': [26, 5],
                                      u'RIGHT': [24, 5],
                                      u'TOP': [23, 5]}},
           u'11': {u'name': u'Repeating Command Block (Conditional, South)',
                   u'tex_direction': {u'BACKWARD': [22, 1],
                                      u'BOTTOM': [25, 5],
                                      u'LEFT': [24, 5],
                                      u'RIGHT': [26, 5],
                                      u'TOP': [25, 5]}},
           u'12': {u'name': u'Repeating Command Block (Conditional, West)',
                   u'tex_direction': {u'BACKWARD': [26, 5],
                                      u'BOTTOM': [26, 5],
                                      u'FORWARD': [24, 5],
                                      u'LEFT': [22, 1],
                                      u'TOP': [26, 5]}},
           u'13': {u'name': u'Repeating Command Block (Conditional, East)',
                   u'tex_direction': {u'BACKWARD': [24, 5],
                                      u'BOTTOM': [24, 5],
                                      u'FORWARD': [26, 5],
                                      u'RIGHT': [22, 1],
                                      u'TOP': [24, 5]}},
           u'2': {u'name': u'Repeating Command Block (Not Conditional, North)',
                  u'tex_direction': {u'BOTTOM': [27, 5],
                                     u'FORWARD': [22, 1],
                                     u'LEFT': [30, 5],
                                     u'RIGHT': [28, 5],
                                     u'TOP': [27, 5]}},
           u'3': {u'name': u'Repeating Command Block (Not Conditional, South)',
                  u'tex_direction': {u'BACKWARD': [22, 1],
                                     u'BOTTOM': [29, 5],
                                     u'LEFT': [28, 5],
                                     u'RIGHT': [30, 5],
                                     u'TOP': [29, 5]}},
           u'4': {u'name': u'Repeating Command Block (Not Conditional, West)',
                  u'tex_direction': {u'BACKWARD': [30, 5],
                                     u'BOTTOM': [30, 5],
                                     u'FORWARD': [28, 5],
                                     u'LEFT': [22, 1],
                                     u'TOP': [30, 5]}},
           u'5': {u'name': u'Repeating Command Block (Not Conditional, East)',
                  u'tex_direction': {u'BACKWARD': [28, 5],
                                     u'BOTTOM': [28, 5],
                                     u'FORWARD': [30, 5],
                                     u'RIGHT': [22, 1],
                                     u'TOP': [28, 5]}},
           u'8': {u'name': u'Repeating Command Block (Conditional, Down)',
                  u'tex_direction': {u'BACKWARD': [25, 5],
                                     u'BOTTOM': [22, 1],
                                     u'FORWARD': [25, 5],
                                     u'SIDES': [25, 5]}},
           u'9': {u'name': u'Repeating Command Block (Conditional, Up)',
                  u'tex_direction': {u'BACKWARD': [23, 5],
                                     u'FORWARD': [23, 5],
                                     u'SIDES': [23, 5],
                                     u'TOP': [22, 1]}}},
 u'id': 188,
 u'idStr': u'repeating_command_block',
 u'mapcolor': [200, 200, 200],
 u'name': u'Repeating Command Block',
 u'tex': [22, 4]}
```
As you can see there, data value 13 looks correct, but when I import the schematic mentioned in my OP, "Repeating Command Block (Conditional, East)" (DV 13) gets changed to "Repeating Command Block (Not Conditional, Down)" and any NBT data gets cleared. 

Even if it was defined incorrectly in blocks.json (which I don't believe is the case), wouldn't the NBT data still pass over?

**Comment by LaChal** [comment]
Asking to print the Json definition, will, hmm, print it...
You can use the result of the query to correct what you need in the NBT data of the entities/tile entities.

I suggest you to load the schematic directly in your filter, and not to import it using the 'classic' way.
You'll be able to reconstruct it with the desired game version data.

Note that internal MCEdit schematic instances are derived from the base class for any world and have a `defIds` member, which is a `MCEditDefsIds` instance.

**Comment by bman92102** [comment]
Should I make a new issue for this bug? Or change the original post since now we know it isn't specific to those blocks? Thanks! 😄

**Comment by bman92102** [comment]
@LaChal Can you re-open this issue? Thanks!

**Comment by LaChal** [comment]
Done.

**Comment by bman92102** [comment]
@LaChal The issue is still not open for me. Are you sure it's open?

**Comment by LaChal** [comment]
Related to #820? (Rhetoric question :wink:)

**Comment by bman92102** [comment]
I would say that issue may not be related since the data values of the blocks are wrong from only certain data values. The blocks themselves convert fine for this issue.

**Comment by OnlyBMan** [comment]
I know it's been a year, but now this bug is behaving somewhat differently. When I made a world with each trapdoor id and copied it to PE, all the ids show correctly, except when it's on a block. I've linked examples of the worlds and for the trapdoor on blocks, they have different ids. Slabs still behave like they did a year ago unfortunately. 

[Trapdoor Example PC.zip](https://github.com/Podshot/MCEdit-Unified/files/2300861/Trapdoor.Example.PC.zip)

[Trapdoor Example PE.zip](https://github.com/Podshot/MCEdit-Unified/files/2300863/Trapdoor.Example.PE.zip)

**Comment by gentlegiantJGC** [comment]
I know this is still an issue but can I suggest you check out MCCToolChest PE to convert the world to a bedrock world first. That should solve your issues

**Comment by OnlyBMan** [comment]
I know MCCToolChestPE can convert the worlds just fine, I've been using it for a while now, it's just that I want to be able to use schematics in Win 10 Edition worlds and I've been looking through my Github and found this issue and wanted to see if it still happens. But thanks for your suggestion anyway!
